### PR TITLE
added function to ignore spaces on non-korean and non-ascii symbols

### PR DESCRIPTION
**Pull request by ksh108405**
Created a simple function to solve #52.
This code add new parameter `only_ko` on `__call__` of `Spacing` class.
The `only_ko` parameter works on `make_pred_sents` method, and when it is `True`, It only put spaces when current character is (korean or ascii-symbol) or next character is (korean or ascii-symbol).
default is set to `False`, so I expect there's no compatibility issues.

### CODE REVIEW

**Comment by ksh108405** [comment]
I'm improving it by completely subtract non-korean or non-ascii-symbol before model prediction, then merges it again on `make_pred_sents`.
It will be able to solve the issue better.

**Comment by ksh108405** [comment]
Now support **customizable pattern** to ignore (not only Korean or ascii-symbol), based on regex pattern.
(default is my own regex to match non-Korean and non-ascii symbol characters, or words.)

Added both pre-processing (delete characters before model prediction, then merges it), and post-processing (ignore spaces on characters which match with pattern).

However, the issue **still remains** both pre-processing and post-processing.
The former has an issue of whether to put space **before** the subtracted text or **after** of it.
The latter **not completely solve** #52, since English in model input can cause incorrect outputs.
So, I added another option to combine both, which the model predicts on both pre-processed text and original text.
It works like pre-processing strategy, but uses predictions from the original text to whether to put space after or before the subtracted text. (But it has to predict **twice**, which almost doubles the time consumption.)

Both can be turned on by the `ignore` parameter.
`ignore=none`: default
`ignore=pre`: ignore by pre-processing
`ignore=pre2`: combined (see above)
`ignore=post`: ignore by post-processing

**Comment by haven-jeon** [comment]
PR 주셔서 감사합니다.
사용자 분들의 이해를 돕기 위해 README.md 업데이트 부탁드려도 될까요?

**Comment by ksh108405** [comment]
Updated README.md with explanations and examples for `ignore` and `ignore_pattern` parameter.

**Comment by haven-jeon** [comment]
감사합니다. merge 했어요..

**Pull request merged**
